### PR TITLE
First draft of showing lit ways

### PR DESCRIPTION
**Pull request by cincodenada**
I took a hack at implementing #11 and it was pretty straightforward - even though the query didn't return ways, there was code to handle ways as points, so just adding the extra line to the query caused points to show up.

But having the ways as points doesn't show them well, so I changed the way handling to show them as lines. I had to change the logic a bit, I hope I didn't break anything there.

It seems to work well, but of course it downloads way more data now, which is probably not what we want. So, I'm not sure if this is useful for the main site, but here it is for reference at least.

### CODE REVIEW

**Comment by sb12** [comment]
Thank you for the code, and also thanks to @JesseWeinstein for the first suggestion.
Showing lit ways was not the original idea of this tool, but I am happy to add the lit ways as a second layer, if there is demand for it. I was a bit critical, whether the overpass api and the leaflet map can handle that much data, but in my first tests in well mapped places it seems to be ok. 
I have some improvements though I would like to see before merging:

- Please add it as a separate layer, so that you can switch it on and off separately from the single street lights
- You can run the `lit=yes` query as a separate overpass query with `out skel` at the end, which will only load the geometries and not the tags and reduces the size of the loaded data
- For the glowing it might be better to just use a light grey instead of opacity, so that overlapping and crossing ways do not become lighter.

**Comment by JesseWeinstein** [comment]
@cincodenada -- thank you so much for coming up with an implementation of this! 

@sb12 -- and thank you for considering merging it. Your suggestions make a lot of sense, and (because I'm curious) I'm going to dig into implementing them. I'll post whatever progress I make tonight, so @cincodenada can see it (and use or ignore it as desired).

**Comment by JesseWeinstein** [comment]
And implemented the suggestions, available here: https://github.com/cincodenada/OSMStreetLight/pull/1

**Comment by cincodenada** [comment]
Okay, I've merged JesseWeinsteins PR which looks great. I also added translations for the layer name - please check on the German!

I also added the last two commits that are optional to change how it behaves. With those commits it will not load the Lit ,Streets layer by default, and only request the way data if the LitStreets layer is shown. The second commit adds a query parameter to restore the behavior of loading the Lit Streets layer at the start.

**Comment by sb12** [comment]
Thanks to both of you for the contributions. It looks ok to me, I did not find any issues.

**Pull request merged**
